export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
}

export const userConstants = {
    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE'
}


export const categoryConstansts = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
    ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: "ADD_NEW_CATEGORY_FAILURE",
    UPDATE_CATEGORIES_REQUEST: "UPDATE_CATEGORIES_REQUEST",
    UPDATE_CATEGORIES_SUCCESS: "UPDATE_CATEGORIES_SUCCESS",
    UPDATE_CATEGORIES_FAILURE: "UPDATE_CATEGORIES_FAILURE",
    DELETE_CATEGORIES_REQUEST: "DELETE_CATEGORIES_REQUEST",
    DELETE_CATEGORIES_SUCCESS: "DELETE_CATEGORIES_SUCCESS",
    DELETE_CATEGORIES_FAILURE: "DELETE_CATEGORIES_FAILURE",
};

export const productConstants = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
  
    DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
    DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
    DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",

    GET_PRODUCT_BY_ID_REQUEST: "GET_PRODUCT_BY_ID_REQUEST",
    GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
    GET_PRODUCT_BY_ID_FAILURE: "GET_PRODUCT_BY_ID_FAILURE",
  
    ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

    EDIT_PRODUCT_REQUEST: "EDIT_PRODUCT_REQUEST",
    EDIT_PRODUCT_SUCCESS: "EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_FAILURE: "EDIT_PRODUCT_FAILURE",
};
export const actorConstants = {
    GET_ALL_ACTORS_REQUEST: "GET_ALL_ACTORS_REQUEST",
    GET_ALL_ACTORS_SUCCESS: "GET_ALL_ACTORS_SUCCESS",
    GET_ALL_ACTORS_FAILURE: "GET_ALL_ACTORS_FAILURE",
    ADD_NEW_ACTORS_REQUEST: "ADD_NEW_ACTORS_REQUEST",
    ADD_NEW_ACTORS_FAILURE: "ADD_NEW_ACTORS_FAILURE",
    ADD_NEW_ACTORS_SUCCESS: "ADD_NEW_ACTORS_SUCCESS",
    DELETE_ACTOR_BY_ID_REQUEST: "DELETE_ACTOR_BY_ID_REQUEST",
    DELETE_ACTOR_BY_ID_SUCCESS: "DELETE_ACTOR_BY_ID_SUCCESS",
    DELETE_ACTOR_BY_ID_FAILURE: "DELETE_ACTOR_BY_ID_SUCCESS",
  
};

export const countryConstansts = {
    GET_ALL_COUNTRY_REQUEST: "GET_ALL_COUNTRY_REQUEST",
    GET_ALL_COUNTRY_SUCCESS: "GET_ALL_COUNTRY_SUCCESS",
    GET_ALL_COUNTRY_FAILURE: "GET_ALL_COUNTRY_FAILURE",
    ADD_NEW_COUNTRY_REQUEST: "ADD_NEW_COUNTRY_REQUEST",
    ADD_NEW_COUNTRY_FAILURE: "ADD_NEW_COUNTRY_FAILURE",
    ADD_NEW_COUNTRY_SUCCESS: "ADD_NEW_COUNTRY_SUCCESS",
    UPDATE_COUNTRY_REQUEST: "UPDATE_COUNTRY_REQUEST",
    UPDATE_COUNTRY_SUCCESS: "UPDATE_COUNTRY_SUCCESS",
    UPDATE_COUNTRY_FAILURE: "UPDATE_COUNTRY_FAILURE",
    DELETE_COUNTRY_REQUEST: "DELETE_COUNTRY_REQUEST",
    DELETE_COUNTRY_SUCCESS: "DELETE_COUNTRY_SUCCESS",
    DELETE_COUNTRY_FAILURE: "DELETE_COUNTRY_FAILURE",
};